### ISSUE TITLE
Появляется ник-нейм когда игрок попадает в воду

### ISSUE THREAD

**Issue by MirFlames** [HolyGolf/HideNickNames#3]
Привет, заметил в коде русские коменты поэтому не буду ебаться с английским.
При выключенных никах когда игрок оказывается в воде ник сразу появляется. Пофикси пожалуйста

**Comment by HolyGolf** [comment]
> Привет, заметил в коде русские коменты поэтому не буду ебаться с английским.
> 
> При выключенных никах когда игрок оказывается в воде ник сразу появляется. Пофикси пожалуйста

Ох, понял. Подправлю.

**Comment by HolyGolf** [comment]
> Привет, заметил в коде русские коменты поэтому не буду ебаться с английским.
> При выключенных никах когда игрок оказывается в воде ник сразу появляется. Пофикси пожалуйста

Ох, я понял. Хорошо, исправлю.

**Comment by HolyGolf** [comment]
Исправил
