### ISSUE TITLE
После перезапуска сервера у всех игроков остались включенные ники

### ISSUE THREAD

**Issue by MirFlames** [HolyGolf/HideNickNames#4]
После перезапуска сервера у всех игроков остались включенные ники. Несмотря на то, что в настройках они по-дефолту отключены

**Comment by HolyGolf** [comment]
> После перезапуска сервера у всех игроков остались включенные ники. Несмотря на то, что в настройках они по-дефолту отключены

Хорошо, я подправлю это.

**Comment by MirFlames** [comment]
Есть идея в чем может быть проблема? После того как поставил CoreProtect и двух перезапусков все видят ники у друг друга

**Comment by HolyGolf** [comment]
Скорее всего я накосячил в коде. А ошибок никаких в консоли нет?

**Comment by MirFlames** [comment]
Никаких ошибок

**Comment by HolyGolf** [comment]
Я просмотрел код и оказалось, что я забыл поменять конфиг. `Hide_NameTags` отвечает за включение и отключение плагина . Что-нибудь происходит при команду /hnames on? А так же какие установлены плагины?

**Comment by MirFlames** [comment]
Разве что сообщение в чат отправляется при /hnames on, больше ничего.
Плагины: BetterSleeping3, CoreProtect, HideNickNames, LuckPerms, OpenRP, Playtime, SkinsRestorer, SuperLogin

**Comment by HolyGolf** [comment]
Так, я немного поигрался с CoreProtect вместе с моим плагином и ничего такого не случилось. Остальные плагины, которые ты перечислил - не должны влиять на работу HideNickNames. Я выпустил версию 2.4.2 с мелкими изменениями в коде, есть шанс что проблема решится. Пока-что закрывать данную ветку не буду.

**Comment by HolyGolf** [comment]
Вопрос: На версии "2.4.2" ники же скрываются?

**Comment by Nextler** [comment]
I have the same problem with the rHideTags plugin working, but it's too old

**Comment by HolyGolf** [comment]
> I have the same problem with the rHideTags plugin working, but it's too old
I checked everything and everything should work. Have you tried the "/hnames on" command?

**Comment by MirFlames** [comment]
Ошибка не пропала, игроки видят ники друг друга(

**Comment by HolyGolf** [comment]
> Ошибка не пропала, игроки видят ники друг друга(

Понял. Хорошо, я в течении недели осмотрю код и перепишу некоторые моменты.
